/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package marblehole;

import javax.swing.JOptionPane;

/**
 *
 * @author Java_Rmutt
 */
public class mainFrame extends javax.swing.JFrame {

    /**
     * Creates new form mainFrame
     */
    public mainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn00 = new javax.swing.JButton();
        btn15 = new javax.swing.JButton();
        btn14 = new javax.swing.JButton();
        btn01 = new javax.swing.JButton();
        btn13 = new javax.swing.JButton();
        btn02 = new javax.swing.JButton();
        btn12 = new javax.swing.JButton();
        btn03 = new javax.swing.JButton();
        btn11 = new javax.swing.JButton();
        btn04 = new javax.swing.JButton();
        btn10 = new javax.swing.JButton();
        btn05 = new javax.swing.JButton();
        txtP2Score = new javax.swing.JTextField();
        txtP1Score = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn00.setText("7");
        btn00.setName("btn1P0"); // NOI18N
        btn00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn00ActionPerformed(evt);
            }
        });

        btn15.setText("7");
        btn15.setEnabled(false);
        btn15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn15ActionPerformed(evt);
            }
        });

        btn14.setText("7");
        btn14.setEnabled(false);
        btn14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn14ActionPerformed(evt);
            }
        });

        btn01.setText("7");
        btn01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn01ActionPerformed(evt);
            }
        });

        btn13.setText("7");
        btn13.setEnabled(false);
        btn13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn13ActionPerformed(evt);
            }
        });

        btn02.setText("7");
        btn02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn02ActionPerformed(evt);
            }
        });

        btn12.setText("7");
        btn12.setEnabled(false);
        btn12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn12ActionPerformed(evt);
            }
        });

        btn03.setText("7");
        btn03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn03ActionPerformed(evt);
            }
        });

        btn11.setText("7");
        btn11.setEnabled(false);
        btn11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn11ActionPerformed(evt);
            }
        });

        btn04.setText("7");
        btn04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn04ActionPerformed(evt);
            }
        });

        btn10.setText("7");
        btn10.setEnabled(false);
        btn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn10ActionPerformed(evt);
            }
        });

        btn05.setText("7");
        btn05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn05ActionPerformed(evt);
            }
        });

        txtP2Score.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        txtP2Score.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtP2Score.setText("0");
        txtP2Score.setAlignmentX(10.0F);
        txtP2Score.setEnabled(false);

        txtP1Score.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        txtP1Score.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtP1Score.setText("0");
        txtP1Score.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtP1Score.setEnabled(false);
        txtP1Score.setName("txtBucket2"); // NOI18N
        txtP1Score.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtP1ScoreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtP2Score, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn00, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn01, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn02, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn03, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn04, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn05, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn15, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn14, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn13, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn12, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn11, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn10, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtP1Score, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn01, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btn00, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn02, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn03, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn04, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn05, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn15, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn14, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn13, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn12, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn11, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn10, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtP2Score)
                    .addComponent(txtP1Score))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtP1ScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtP1ScoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtP1ScoreActionPerformed

    private void btn00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn00ActionPerformed
        btnEvent(0, 0);
    }//GEN-LAST:event_btn00ActionPerformed

    private void btn15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn15ActionPerformed
        btnEvent(1, 5);
    }//GEN-LAST:event_btn15ActionPerformed

    private void btn02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn02ActionPerformed
        btnEvent(0, 2);
    }//GEN-LAST:event_btn02ActionPerformed

    private void btn03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn03ActionPerformed
        btnEvent(0, 3);
    }//GEN-LAST:event_btn03ActionPerformed

    private void btn04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn04ActionPerformed
        btnEvent(0, 4);
    }//GEN-LAST:event_btn04ActionPerformed

    private void btn05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn05ActionPerformed
        btnEvent(0, 5);
    }//GEN-LAST:event_btn05ActionPerformed

    private void btn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn10ActionPerformed
        btnEvent(1, 0);
    }//GEN-LAST:event_btn10ActionPerformed

    private void btn11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn11ActionPerformed
        btnEvent(1, 1);
    }//GEN-LAST:event_btn11ActionPerformed

    private void btn12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn12ActionPerformed
        btnEvent(1, 2);
    }//GEN-LAST:event_btn12ActionPerformed

    private void btn13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn13ActionPerformed
        btnEvent(1, 3);
    }//GEN-LAST:event_btn13ActionPerformed

    private void btn14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn14ActionPerformed
        btnEvent(1, 4);
    }//GEN-LAST:event_btn14ActionPerformed

    private void btn01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn01ActionPerformed
        btnEvent(0, 1);
    }//GEN-LAST:event_btn01ActionPerformed

    private static cycle c = new cycle();
    private int[][] resultData = new int[2][6];
    private int[][] data = new int[2][6];
    private int dataScore[] = new int[2];

    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainFrame().setVisible(true);
                c.cycle(2, 6, 2);
            }
        });

    }

    public void btnEvent(int t, int p) {
        boolean endTurn = true;

        data = getData();
        // Position, Turn
        endTurn = c.putDownStone(p, t, data);
        data = c.getData();
        dataScore = c.getScore();
        setDisplay();
        if (!endTurn) {
            if (t == 0) {
                setControl(false);
            } else {
                setControl(true);
            }
        }
        findWinner();        
        if(data[0][0] == 0 && data[0][1] == 0 && data[0][2] == 0 && data[0][3] == 0 && data[0][4] == 0 && data[0][5] == 0){
            setControl(false);
        }else if(data[1][0] == 0 && data[1][1] == 0 && data[1][2] == 0 && data[1][3] == 0 && data[1][4] == 0 && data[1][5] == 0){
            setControl(true);
        }
        
    }
    
    public void findWinner(){
        int P1 = Integer.parseInt(txtP1Score.getText());
        int P2 = Integer.parseInt(txtP1Score.getText());
        /*if(P1 + P2 == 84){
            if(P1 > P2){
                JOptionPane.showMessageDialog(rootPane,"Player1 win!!!");
            }else if(P1 < P2){
                JOptionPane.showMessageDialog(rootPane,"Player2 win!!!");
            }else if(P1 == P2){
                JOptionPane.showMessageDialog(rootPane,"Drawn!!!");
            }
        }*/
        if(P1 > 42){
            JOptionPane.showMessageDialog(rootPane,"Player1 win!!!");
        }else if(P2 > 42){
            JOptionPane.showMessageDialog(rootPane,"Player2 win!!!");
        }
    }

    public void setDisplay() {
        btn00.setText("" + data[0][0]);
        btn01.setText("" + data[0][1]);
        btn02.setText("" + data[0][2]);
        btn03.setText("" + data[0][3]);
        btn04.setText("" + data[0][4]);
        btn05.setText("" + data[0][5]);

        btn10.setText("" + data[1][0]);
        btn11.setText("" + data[1][1]);
        btn12.setText("" + data[1][2]);
        btn13.setText("" + data[1][3]);
        btn14.setText("" + data[1][4]);
        btn15.setText("" + data[1][5]);

        txtP1Score.setText("" + dataScore[0]);
        txtP2Score.setText("" + dataScore[1]);
    }

    public void setControl(boolean data) {
        btn00.setEnabled(data);
        btn01.setEnabled(data);
        btn02.setEnabled(data);
        btn03.setEnabled(data);
        btn04.setEnabled(data);
        btn05.setEnabled(data);

        btn10.setEnabled(!data);
        btn11.setEnabled(!data);
        btn12.setEnabled(!data);
        btn13.setEnabled(!data);
        btn14.setEnabled(!data);
        btn15.setEnabled(!data);

        txtP1Score.setText("" + dataScore[0]);
        txtP2Score.setText("" + dataScore[1]);
    }

    public int[][] getData() {
        int[][] tmp = new int[2][6];

        tmp[0][0] = Integer.parseInt(btn00.getText());
        tmp[0][1] = Integer.parseInt(btn01.getText());
        tmp[0][2] = Integer.parseInt(btn02.getText());
        tmp[0][3] = Integer.parseInt(btn03.getText());
        tmp[0][4] = Integer.parseInt(btn04.getText());
        tmp[0][5] = Integer.parseInt(btn05.getText());

        tmp[1][0] = Integer.parseInt(btn10.getText());
        tmp[1][1] = Integer.parseInt(btn11.getText());
        tmp[1][2] = Integer.parseInt(btn12.getText());
        tmp[1][3] = Integer.parseInt(btn13.getText());
        tmp[1][4] = Integer.parseInt(btn14.getText());
        tmp[1][5] = Integer.parseInt(btn15.getText());

        return tmp;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn00;
    private javax.swing.JButton btn01;
    private javax.swing.JButton btn02;
    private javax.swing.JButton btn03;
    private javax.swing.JButton btn04;
    private javax.swing.JButton btn05;
    private javax.swing.JButton btn10;
    private javax.swing.JButton btn11;
    private javax.swing.JButton btn12;
    private javax.swing.JButton btn13;
    private javax.swing.JButton btn14;
    private javax.swing.JButton btn15;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtP1Score;
    private javax.swing.JTextField txtP2Score;
    // End of variables declaration//GEN-END:variables
}
